#!/bin/bash
rm -rf /dev/pci_skel
rm -rf /dev/pci_skel_2
rm -rf /dev/pci_skel_3
rm -rf /dev/pci_skel_4
rm -rf /dev/pci_skel_5

mknod /dev/pci_skel c 241 1
mknod /dev/pci_skel_2 c 241 2
mknod /dev/pci_skel_3 c 241 3
mknod /dev/pci_skel_4 c 241 4
mknod /dev/pci_skel_5 c 241 5

chown root /dev/pci_skel
chmod 666 /dev/pci_skel

chown root /dev/pci_skel_2
chmod 666 /dev/pci_skel_2

chown root /dev/pci_skel_3
chmod 666 /dev/pci_skel_3

chown root /dev/pci_skel_4
chmod 666 /dev/pci_skel_4

chown root /dev/pci_skel_5
chmod 666 /dev/pci_skel_5

ls -al /dev/pci_skel
insmod ./sv_driver.ko device_id=0x7028 major=241
lsmod | grep pci_skel

